### ISSUE TITLE
約定チェックができない＆キャンセルで異常終了？

### ISSUE THREAD

**Issue by do-gugan** [bitrinjani/rinjani#1]
Qiitaのコメント欄ではお世話になりました。どちらに書くか迷いましたが現象別にまとまった方がいいかと思いこちらにIssue立てさせていただきます。単純な設定ミスだったらご勘弁くださいませ。

お陰様で取引が実行されるところまでいったのですが、約定の確認がうまくいかないらしく、MaxRetryCountやOrderStatusCheckIntervalを増やしてみても最後にはMax retry count reached.になりアプリケーションが終了しています。各取引所のログをみるに約定はしているようです。これが書いてらっしゃるAPIの品質による問題でしょうか。
ちなみに現在はbitFlyerよりCoincheckの方がBTCが高いので、前者で買って後者で売る動作になっていると思います。ということはCoincheck側の約定が確認できてないんでしょうか、、

2017/09/19 22:37:53 Warn [Rinjani.Arbitrager.CheckOrderState] Sell leg is not filled yet. Pending size is 0.02.
2017/09/19 22:37:56 Info [Rinjani.Arbitrager.CheckOrderState] >>Order check attempt 30.
2017/09/19 22:37:56 Info [Rinjani.Arbitrager.CheckOrderState] >>Checking if both legs are done or not...
2017/09/19 22:37:57 Warn [Rinjani.Arbitrager.CheckOrderState] Sell leg is not filled yet. Pending size is 0.02.
2017/09/19 22:37:57 Warn [Rinjani.Arbitrager.CheckOrderState] Max retry count reached. Cancelling the pending orders.
2017/09/19 22:37:57 Error [Rinjani.RestUtil.CheckError] BadRequest
2017/09/19 22:37:57 Error [Rinjani.RestUtil.CheckError] {"success":false,"error":"Failed to cancel the order."}
2017/09/19 22:37:57 Error [Rinjani.Arbitrager.QuoteUpdated] {"success":false,"error":"Failed to cancel the order."}

**Comment by do-gugan** [comment]
1時台に再度試したところ、一定の率で約定チェックが通るようになりました。通らないものもリトライ何度かやるうちに通り、アプリが継続的に実行できてる様です。やはり時間帯でAPIの品質が変化するということでしょうか。クライアント側では解決は難しそうですね。

**Comment by bitrinjani** [comment]
また入れ違いになりすいません、昨日同様の問題に気づき以下の修正をいれました。最新版で試していただけますでしょうか?
コインチェックにて、他の取引所と違い売り約定数量がマイナスになる点を見落としていました。
https://github.com/bitrinjani/rinjani/commit/e0c17ed972ca0d16b581cd89b1b6d01e5b704e83
試していただいてありがとうございます。

**Comment by do-gugan** [comment]
こちらこそありがとうございます。プロトタイプということは理解して遊ばせていただいてますので、どうぞマイペースでご対応いただければと。
お陰様でその後は多少の取引が発生しました。ずっとbitFlyer買いCoincheck売りばっかりだったので、一旦決済しようとしたんですが、BF->CCにBTC送金してもCC側は現物で空売りを相殺できないようなのでちょっと大変そうですね。私がよくわかってないせいかも知れませんが、、。とりあえずQUOINEXの書類審査待ちです（現状APIキーが無効なのか例外で落ちます）。
今日の夕方以降はBest AskもBest BidもCCになったままでNo Opputunity続きです。BFもポジションは取得できてるし、生ログにReceived depth from Bitflyer.と出てるので動作としては正常なんでしょうか。一応ご報告です。

2017/09/20 19:34:34.195 Debug [Rinjani.QuoteAggregator.Aggregate] Aggregating quotes...
2017/09/20 19:34:34.195 Debug [Rinjani.Bitflyer.BrokerAdapter.FetchQuotes] Getting depth from Bitflyer...
2017/09/20 19:34:34.733 Debug [Rinjani.Bitflyer.BrokerAdapter.FetchQuotes] Received depth from Bitflyer.
2017/09/20 19:34:34.733 Debug [Rinjani.Coincheck.BrokerAdapter.FetchQuotes] Getting depth from Coincheck...
2017/09/20 19:34:34.779 Debug [Rinjani.Coincheck.BrokerAdapter.FetchQuotes] Received depth from Coincheck.
2017/09/20 19:34:34.779 Info [Rinjani.Arbitrager.QuoteUpdated] --------------------ARBITRAGER--------------------
2017/09/20 19:34:34.792 Info [Rinjani.Arbitrager.Arbitrage] Looking for opportunity...
2017/09/20 19:34:34.792 Info [Rinjani.Arbitrager.Arbitrage] Best ask         :  Coincheck   Ask  434000 8.630
2017/09/20 19:34:34.810 Info [Rinjani.Arbitrager.Arbitrage] Best bid         :  Coincheck   Bid  433400 1.572
2017/09/20 19:34:34.818 Info [Rinjani.Arbitrager.Arbitrage] Spread           : 600
2017/09/20 19:34:34.818 Info [Rinjani.Arbitrager.Arbitrage] Available volume : 1.57
2017/09/20 19:34:34.837 Info [Rinjani.Arbitrager.Arbitrage] Target volume    : 0.5
2017/09/20 19:34:34.837 Info [Rinjani.Arbitrager.Arbitrage] Expected profit  : -300
2017/09/20 19:34:34.858 Info [Rinjani.Arbitrager.Arbitrage] No arbitrage opportunity. Spread is not inverted.
2017/09/20 19:34:34.866 Info [Rinjani.Arbitrager.QuoteUpdated] --------------------------------------------------

ちなみに、BFだけをtrueにした場合は、
Failed to get a spread analysis result. No best bid/ask was found.
と出続けます。

**Comment by bitrinjani** [comment]
>ずっとbitFlyer買いCoincheck売りばっかりだったので

この動きには悩まされますよね。Qiitaに書いた「ポジションの偏り」がまさにこの現象です。取引所間ビットコイン送金を自動化しようかとも検討中です。

>今日の夕方以降はBest AskもBest BidもCCになったままでNo Opputunity続きです。BFもポジションは取得できてるし、生ログにReceived depth from Bitflyer.と出てるので動作としては正常なんでしょうか

取引所2つだと裁定機会がない状態が数十分続くことは正常です。今後対応する取引所を増やしていく予定です。次はZaifを予定しています。

>ちなみに、BFだけをtrueにした場合は、
>Failed to get a spread analysis result. No best bid/ask was found.

取引所一つだと裁定機会はないという前提で作っているので、そのような動作となります。
